name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust + wasm target
        uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown

      - name: Install trunk
        run: cargo install trunk

      - name: Download Tailwind standalone CLI
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss

      - name: Build Tailwind to dist/
        run: ./tailwindcss -i ./public/tailwind.css -o ./public/tailwind.css

      - name: Build with trunk (release)
        run: trunk build --release

      - name: SPA fallback (only needed if you use pretty routes)
        run: cp dist/index.html dist/404.html || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
